name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential jq

    - name: Get latest telegram-integration tag version
      id: tag
      run: |
        TAG=$(curl -s "https://api.github.com/repos/usememos/telegram-integration/tags" | jq -r '.[0].name' | tr -d 'v')
        echo "TAG=$TAG" >> $GITHUB_ENV

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/hu3rror/memos-telegram-integration
        tags: |
          type=raw,value=${{ env.TAG }}
          type=raw,value=latest

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ./
        file: ./Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta.outputs.tags }}